import pandas as pd
import base64
import hashlib
import numpy as np

binsize = config['binsize']
min_mapq = config['min_mapq']

pipeline_dir = config['pipeline_dir']
metadata = pipeline_dir + '/metadata'
scripts_dir = pipeline_dir + '/scripts'
benchmark_dir = pipeline_dir + '/benchmark'

workdir = config['working_dir']
outdir = workdir + '/output'

gurobi_license_file = config['gurobi_license_file']
python_bin = config['python_bin']

ecademix_params = pd.read_csv(config['ecademix_params'], 
    dtype={'patient_id': str, 'max_reads_nonamplicon_cell': int, 'n_amplicons': int, 
    'max_amplicon_cn': int, 'seed': int, 'min_loading': int, 'max_loading': int, 'lambda_x': float, 
    'lambda_x_l1': float, 'lambda_y': float, 'plot_data_vmax': float, 'plot_loading_vmax': float,
    'normalize_data': bool, 'round_cn_normalize': bool, 'cell_weights': bool, 'refit_loadings_lambda_y': float})
ecademix_params = ecademix_params.set_index('patient_id')

min_bamfile_size=3000

regions = pd.read_table(config['regions_table'])
patients = sorted(regions.individual.unique().astype(str))

# list of patients that are mouse, to use correct chromosome list for parallelization
mouse_patients = ['2765_2']

# WARNING: only using most recent aliquot per sample

bamfiles = pd.read_csv(config['bamfiles_table'])
# remove all patients with only empty control BAM files (indicates QC failure)
to_remove = []
for patient_id in patients:
    my_df = bamfiles[bamfiles.isabl_patient_id ==patient_id]
    has_aliquot = False
    for sample_id in my_df.isabl_sample_id.unique():
        sample_df = my_df[my_df.isabl_sample_id == sample_id].sort_values(by='isabl_pk', ascending=False)
        aliquot = sample_df.isabl_aliquot_id.iloc[0]
        if os.path.getsize(sample_df.iloc[0].result_control_filepath) >= min_bamfile_size:
            has_aliquot=True
            break
    if not has_aliquot:
        print("removing patient with no aliquots with sufficiently large control BAMs", patient_id)
        to_remove.append(patient_id)

include: 'rules/count_reads.smk'
include: 'rules/ecademix.smk'
